Repository tqtezos/minter-sdk, pull requests merged in 2021-04, with the labels that each got.

#110 Auction and marketplace with allowlist
  .github/workflows/ci.yml
  packages/minter-contracts/README.md
  packages/minter-contracts/bin-ts/english_auction_fa2_allowlisted.tz.ts
  packages/minter-contracts/bin-ts/english_auction_tez_allowlisted.tz.ts
  packages/minter-contracts/bin-ts/english_auction_tez_permit_allowlisted.tz.ts
  packages/minter-contracts/bin-ts/fa2_allowlisted_swap.tz.ts
  packages/minter-contracts/bin-ts/fa2_whitelisted_swap.tz.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_allowlisted.tz.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez_allowlisted.tz.ts
  packages/minter-contracts/bin/english_auction_fa2_allowlisted.tz
  packages/minter-contracts/bin/english_auction_tez_allowlisted.tz
  packages/minter-contracts/bin/english_auction_tez_permit_allowlisted.tz
  packages/minter-contracts/bin/fa2_allowlisted_swap.tz
  packages/minter-contracts/bin/fixed_price_sale_market_allowlisted.tz
  packages/minter-contracts/bin/fixed_price_sale_market_tez_allowlisted.tz
  packages/minter-contracts/hpack/definitions.yaml
  packages/minter-contracts/index.ts
  packages/minter-contracts/ligo/fa2_modules/allowlist.mligo
  packages/minter-contracts/ligo/src/english_auction/README.md
  packages/minter-contracts/ligo/src/english_auction/english_auction_fa2_allowlisted.mligo
  packages/minter-contracts/ligo/src/english_auction/english_auction_tez_allowlisted.mligo
  packages/minter-contracts/ligo/src/english_auction/english_auction_tez_permit_allowlisted.mligo
  packages/minter-contracts/ligo/src/fixed_price_sale/README.md
  packages/minter-contracts/ligo/src/fixed_price_sale/fixed_price_sale_market_allowlisted.mligo
  packages/minter-contracts/ligo/src/fixed_price_sale/fixed_price_sale_market_tez_allowlisted.mligo
  packages/minter-contracts/ligo/src/swaps/README.md
  packages/minter-contracts/ligo/src/swaps/fa2_allowlisted_swap.mligo
  packages/minter-contracts/package.yaml
  packages/minter-contracts/src-hs/Lorentz/Contracts/EnglishAuction/Allowlisted.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/EnglishAuction/FA2.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/EnglishAuction/Tez.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/EnglishAuction/TezPermit.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/Marketplace/Allowlisted.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/Marketplace/FA2.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/Marketplace/Tez.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/PausableAdminOption.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/Swaps/Allowlisted.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/Swaps/Basic.hs
  packages/minter-contracts/src-hs/Lorentz/Contracts/WhitelistedSwaps.hs
  packages/minter-contracts/src/allowlist.ts
  packages/minter-contracts/src/compile-ligo.ts
  packages/minter-contracts/src/nft-contracts.ts
  packages/minter-contracts/test-hs/Test/Allowlisted.hs
  packages/minter-contracts/test-hs/Test/EnglishAuction/AllowlistedFA2.hs
  packages/minter-contracts/test-hs/Test/EnglishAuction/AllowlistedTez.hs
  packages/minter-contracts/test-hs/Test/EnglishAuction/AllowlistedTezPermit.hs
  packages/minter-contracts/test-hs/Test/EnglishAuction/Util.hs
  packages/minter-contracts/test-hs/Test/Marketplace/AllowlistedFA2.hs
  packages/minter-contracts/test-hs/Test/Marketplace/AllowlistedTez.hs
  packages/minter-contracts/test-hs/Test/Marketplace/Util.hs
  packages/minter-contracts/test-hs/Test/NonPausableSimpleAdmin.hs
  packages/minter-contracts/test-hs/Test/Swaps/Allowlisted.hs
  packages/minter-contracts/test-hs/Test/Swaps/Basic.hs
  packages/minter-contracts/test-hs/Test/Swaps/Util.hs
  packages/minter-contracts/test-hs/Test/Swaps/Whitelisted.hs
  packages/minter-contracts/test-hs/Test/Util.hs
Labels: enhancement, p0

#71 fixed price sale docs
  packages/minter-contracts/bin-ts/fixed_price_sale_market.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_allowlisted.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_allowlisted.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez_allowlisted.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez_allowlisted.types.ts
  packages/minter-contracts/bin/fixed_price_sale_market.tz
  packages/minter-contracts/bin/fixed_price_sale_market_allowlisted.tz
  packages/minter-contracts/bin/fixed_price_sale_market_tez.tz
  packages/minter-contracts/bin/fixed_price_sale_market_tez_allowlisted.tz
  packages/minter-contracts/ligo/src/fixed_price_sale/README.md
  packages/minter-contracts/ligo/src/fixed_price_sale/fixed_price_sale_market.mligo
  packages/minter-contracts/ligo/src/fixed_price_sale/fixed_price_sale_market_tez.mligo
Labels: documentation, p1

#124 README edits
  packages/minter-contracts/ligo/src/fixed_price_sale/README.md
  packages/minter-contracts/ligo/src/minter_collection/editions/README.md
Labels: documentation

#131 Eli/editions v2
  packages/minter-contracts/bin-ts/editions_token_metadata_view.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_asset.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_faucet.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_token_editions.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_token_editions.types.ts
  packages/minter-contracts/bin/editions_token_metadata_view.tz
  packages/minter-contracts/bin/fa2_multi_nft_asset.tz
  packages/minter-contracts/bin/fa2_multi_nft_faucet.tz
  packages/minter-contracts/bin/fa2_multi_nft_token_editions.tz
  packages/minter-contracts/ligo/src/minter_collection/editions/fa2_multi_nft_token_editions.mligo
  packages/minter-contracts/ligo/src/minter_collection/editions/views.mligo
  packages/minter-contracts/ligo/src/minter_collection/nft/fa2_multi_nft_asset.mligo
  packages/minter-contracts/ligo/src/minter_collection/nft/fa2_multi_nft_manager.mligo
  packages/minter-contracts/ligo/src/minter_collection/nft/fa2_multi_nft_token.mligo
  packages/minter-contracts/src/nft-contracts.ts
  packages/minter-contracts/test/editions.test.ts
Labels: enhancement

#139 Eli/editions taquito tests
  packages/minter-contracts/ligo/src/minter_collection/editions/README.md
  packages/minter-contracts/test/auction/fa2-auction-fee.test.ts
  packages/minter-contracts/test/auction/fa2-auction.test.ts
  packages/minter-contracts/test/editions.test.ts
Labels: p0

#136 Remove TS build artifacts from source control
  .github/workflows/ci.yml
  packages/minter-contracts/.gitignore
  packages/minter-contracts/bin-ts/.gitkeep
  packages/minter-contracts/bin-ts/editions_token_metadata_view.code.ts
  packages/minter-contracts/bin-ts/editions_token_metadata_view.types.ts
  packages/minter-contracts/bin-ts/english_auction_fa2.code.ts
  packages/minter-contracts/bin-ts/english_auction_fa2.types.ts
  packages/minter-contracts/bin-ts/english_auction_fa2_allowlisted.code.ts
  packages/minter-contracts/bin-ts/english_auction_fa2_allowlisted.types.ts
  packages/minter-contracts/bin-ts/english_auction_fa2_fixed_fee.code.ts
  packages/minter-contracts/bin-ts/english_auction_fa2_fixed_fee.types.ts
  packages/minter-contracts/bin-ts/english_auction_tez.code.ts
  packages/minter-contracts/bin-ts/english_auction_tez.types.ts
  packages/minter-contracts/bin-ts/english_auction_tez_allowlisted.code.ts
  packages/minter-contracts/bin-ts/english_auction_tez_allowlisted.types.ts
  packages/minter-contracts/bin-ts/english_auction_tez_fixed_fee.code.ts
  packages/minter-contracts/bin-ts/english_auction_tez_fixed_fee.types.ts
  packages/minter-contracts/bin-ts/english_auction_tez_permit.code.ts
  packages/minter-contracts/bin-ts/english_auction_tez_permit.types.ts
  packages/minter-contracts/bin-ts/english_auction_tez_permit_allowlisted.code.ts
  packages/minter-contracts/bin-ts/english_auction_tez_permit_allowlisted.types.ts
  packages/minter-contracts/bin-ts/fa2_allowlisted_swap.code.ts
  packages/minter-contracts/bin-ts/fa2_allowlisted_swap.types.ts
  packages/minter-contracts/bin-ts/fa2_multi_ft_asset.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_ft_asset.types.ts
  packages/minter-contracts/bin-ts/fa2_multi_ft_faucet.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_ft_faucet.types.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_asset.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_asset.types.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_faucet.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_faucet.types.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_token_editions.code.ts
  packages/minter-contracts/bin-ts/fa2_multi_nft_token_editions.types.ts
  packages/minter-contracts/bin-ts/fa2_swap.code.ts
  packages/minter-contracts/bin-ts/fa2_swap.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_allowlisted.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_allowlisted.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_fixed_fee.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_fixed_fee.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez_allowlisted.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_market_tez_allowlisted.types.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_tez_fixed_fee.code.ts
  packages/minter-contracts/bin-ts/fixed_price_sale_tez_fixed_fee.types.ts
  packages/minter-contracts/bin-ts/ticket_auction.code.ts
  packages/minter-contracts/bin-ts/ticket_auction.types.ts
  packages/minter-contracts/bin-ts/ticket_wallet.code.ts
  packages/minter-contracts/bin-ts/ticket_wallet.types.ts
  packages/minter-contracts/bin-ts/type-aliases.ts
  packages/minter-contracts/index.ts
  packages/minter-contracts/package.json
Labels: p2
